#pragma checksum "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1918438df79c9507e79b3085f728fb781ff76c77"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Profiles_Profile), @"mvc.1.0.view", @"/Views/Profiles/Profile.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Profiles/Profile.cshtml", typeof(AspNetCore.Views_Profiles_Profile))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\_ViewImports.cshtml"
using Fortnite_LFG_Hub;

#line default
#line hidden
#line 2 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\_ViewImports.cshtml"
using Fortnite_LFG_Hub.Models;

#line default
#line hidden
#line 2 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
using Fortnite_LFG_Hub.ViewModels;

#line default
#line hidden
#line 3 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
using BusinessLayer.Logic;

#line default
#line hidden
#line 4 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
using BusinessLayer;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"1918438df79c9507e79b3085f728fb781ff76c77", @"/Views/Profiles/Profile.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"6488c9f39a0d2cb16d2388629acb7f83bffadd62", @"/Views/_ViewImports.cshtml")]
    public class Views_Profiles_Profile : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<BusinessLayer.Profile>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "Profiles", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "EditProfile", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/images/Profile/Player.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("name", "Comment", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Profile", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "Comment", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "DeleteComment", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(192, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 7 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
  
    ViewData["Title"] = "Profile";

#line default
#line hidden
            BeginContext(237, 57, true);
            WriteLiteral("\r\n<h1 style=\"border-bottom:solid 1px;padding-bottom:3px\">");
            EndContext();
            BeginContext(295, 14, false);
#line 11 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                  Write(Model.Username);

#line default
#line hidden
            EndContext();
            BeginContext(309, 143, true);
            WriteLiteral("</h1> <!-- Picture should come here too -->\r\n<br />\r\n<br />\r\n\r\n<div class=\"container\">\r\n    <div class=\"row\">\r\n        <div class=\"col-lg-9\">\r\n");
            EndContext();
#line 18 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
             if (HttpContextAccessor.HttpContext.Session.Get<int>("UserId") == Model.UserId)
            {
                // If the session UserId is the same as the current profile in the view, we can edit it.

#line default
#line hidden
            BeginContext(667, 16, true);
            WriteLiteral("                ");
            EndContext();
            BeginContext(683, 104, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "75eedff73d6745de8efed3801ef49191", async() => {
                BeginContext(766, 17, true);
                WriteLiteral("Edit Achievements");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_0.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_1.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
            if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
            {
                throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-id", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
            }
            BeginWriteTagHelperAttribute();
#line 21 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                                        WriteLiteral(Model.UserId);

#line default
#line hidden
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = __tagHelperStringValueBuffer;
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-id", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(787, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 22 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
            }

#line default
#line hidden
            BeginContext(802, 8, true);
            WriteLiteral("<br />\r\n");
            EndContext();
#line 23 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
             if (Model.Flairs.Count > 0)
            {
                foreach (var flair in Model.Flairs)
                {
                    string cleanFlair = flair.ToString().Replace("_", " ");
                    if (flair == Flairs.Top_50 || flair == Flairs.Top_25)
                    {

#line default
#line hidden
            BeginContext(1114, 58, true);
            WriteLiteral("                        <span class=\"label label-success\">");
            EndContext();
            BeginContext(1173, 10, false);
#line 30 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                     Write(cleanFlair);

#line default
#line hidden
            EndContext();
            BeginContext(1183, 9, true);
            WriteLiteral("</span>\r\n");
            EndContext();
#line 31 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                    }
                    else
                    {

#line default
#line hidden
            BeginContext(1264, 58, true);
            WriteLiteral("                        <span class=\"label label-primary\">");
            EndContext();
            BeginContext(1323, 10, false);
#line 34 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                     Write(cleanFlair);

#line default
#line hidden
            EndContext();
            BeginContext(1333, 9, true);
            WriteLiteral("</span>\r\n");
            EndContext();
#line 35 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                    }
                }
            }

#line default
#line hidden
            BeginContext(1399, 40, true);
            WriteLiteral("            <br />\r\n            <br />\r\n");
            EndContext();
#line 40 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
             if (Model.Achievements.Count > 0)
            {

#line default
#line hidden
            BeginContext(1502, 365, true);
            WriteLiteral(@"                <table class=""table table-bordered table-hover table table-striped"">
                    <tr>
                        <th colspan=""2"" class=""text-center bg-info h4""><b>Achievements</b></th>
                    </tr>
                    <tr>
                        <th>#</th>
                        <th>Event</th>
                    </tr>
");
            EndContext();
#line 50 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                     foreach (var achievement in Model.Achievements)
                    {

#line default
#line hidden
            BeginContext(1960, 30, true);
            WriteLiteral("                        <tr>\r\n");
            EndContext();
#line 53 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                             if (achievement.Rank <= 50)
                            {

#line default
#line hidden
            BeginContext(2079, 100, true);
            WriteLiteral("                                <td class=\"col-md-1 text-center\" style=\"background-color: #FFD739;\">");
            EndContext();
            BeginContext(2180, 16, false);
#line 55 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                                                               Write(achievement.Rank);

#line default
#line hidden
            EndContext();
            BeginContext(2196, 7, true);
            WriteLiteral("</td>\r\n");
            EndContext();
#line 56 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                            }
                            else if(achievement.Rank > 50 && achievement.Rank <= 500)
                            {

#line default
#line hidden
            BeginContext(2352, 111, true);
            WriteLiteral("                                <td class=\"col-md-1 text-center\" style=\"background-color: #0094B2;color:white\">");
            EndContext();
            BeginContext(2464, 16, false);
#line 59 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                                                                          Write(achievement.Rank);

#line default
#line hidden
            EndContext();
            BeginContext(2480, 7, true);
            WriteLiteral("</td>\r\n");
            EndContext();
#line 60 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                            }
                            else
                            {

#line default
#line hidden
            BeginContext(2583, 92, true);
            WriteLiteral("                            <td class=\"col-md-1 text-center bg-primary\" style=\"color:white\">");
            EndContext();
            BeginContext(2676, 16, false);
#line 63 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                                                       Write(achievement.Rank);

#line default
#line hidden
            EndContext();
            BeginContext(2692, 7, true);
            WriteLiteral("</td>\r\n");
            EndContext();
#line 64 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                            }

#line default
#line hidden
            BeginContext(2730, 32, true);
            WriteLiteral("                            <td>");
            EndContext();
            BeginContext(2763, 17, false);
#line 65 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                           Write(achievement.Event);

#line default
#line hidden
            EndContext();
            BeginContext(2780, 38, true);
            WriteLiteral("</td>\r\n                        </tr>\r\n");
            EndContext();
#line 67 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                    }

#line default
#line hidden
            BeginContext(2841, 26, true);
            WriteLiteral("                </table>\r\n");
            EndContext();
#line 69 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
            }
            else
            {

#line default
#line hidden
            BeginContext(2915, 68, true);
            WriteLiteral("                <h3>This user has not shared any achievements</h3>\r\n");
            EndContext();
#line 73 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
            }

#line default
#line hidden
            BeginContext(2998, 184, true);
            WriteLiteral("        </div>\r\n        <div class=\"col-lg-2\">\r\n            <table class=\"table-bordered\">\r\n                <tr>\r\n                    <th colspan=\"2\" class=\"text-center bg-info h4\"><b>");
            EndContext();
            BeginContext(3183, 14, false);
#line 78 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                                 Write(Model.Username);

#line default
#line hidden
            EndContext();
            BeginContext(3197, 118, true);
            WriteLiteral("</b></th>\r\n                </tr>\r\n                <tr>\r\n                    <td colspan=\"2\"><div class=\"center-block\">");
            EndContext();
            BeginContext(3315, 41, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "6687295bf5ca47948d699b7f57ae6c80", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(3356, 318, true);
            WriteLiteral(@"</div></td>
                </tr>
                <tr>
                    <th colspan=""2"" class=""text-center bg-info h4""><b>Additional Information</b></th>
                </tr>
                <tr>
                    <td>
                        <br />
                        <b>Region: &nbsp; &nbsp;</b>
");
            EndContext();
#line 90 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                         if (Model.Region != BusinessLayer.Regions._)
                        {

#line default
#line hidden
            BeginContext(3772, 34, true);
            WriteLiteral("                            <span>");
            EndContext();
            BeginContext(3807, 23, false);
#line 92 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                             Write(Model.Region.ToString());

#line default
#line hidden
            EndContext();
            BeginContext(3830, 9, true);
            WriteLiteral("</span>\r\n");
            EndContext();
#line 93 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                        }
                        else
                        {

#line default
#line hidden
            BeginContext(3923, 57, true);
            WriteLiteral("                            <span>Region unknown</span>\r\n");
            EndContext();
#line 97 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                        }

#line default
#line hidden
            BeginContext(4007, 32, true);
            WriteLiteral("                        <br />\r\n");
            EndContext();
#line 99 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                         if (Model.Looking)
                        {

#line default
#line hidden
            BeginContext(4111, 67, true);
            WriteLiteral("                            <span><b>Looking For Group</b></span>\r\n");
            EndContext();
#line 102 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                        }
                        else
                        {

#line default
#line hidden
            BeginContext(4262, 71, true);
            WriteLiteral("                            <span><b>Not Looking For Group</b></span>\r\n");
            EndContext();
#line 106 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                        }

#line default
#line hidden
            BeginContext(4360, 64, true);
            WriteLiteral("                        <br />\r\n                        <br />\r\n");
            EndContext();
#line 109 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                         if (!string.IsNullOrWhiteSpace(Model.FreeText))
                        {

#line default
#line hidden
            BeginContext(4525, 34, true);
            WriteLiteral("                            <span>");
            EndContext();
            BeginContext(4560, 14, false);
#line 111 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                             Write(Model.FreeText);

#line default
#line hidden
            EndContext();
            BeginContext(4574, 9, true);
            WriteLiteral("</span>\r\n");
            EndContext();
#line 112 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                        }
                        else
                        {

#line default
#line hidden
            BeginContext(4667, 94, true);
            WriteLiteral("                            <span>This user has not shared any additional information</span>\r\n");
            EndContext();
#line 116 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                        }

#line default
#line hidden
            BeginContext(4788, 320, true);
            WriteLiteral(@"                        <br />
                        <br />
                    </td>
                </tr>
                <tr>
                    <th colspan=""2"" class=""text-center bg-info h4""><b>Social Media</b></th>
                </tr>
                <tr>
                    <td class=""text-center"">
");
            EndContext();
#line 126 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                         if (!string.IsNullOrWhiteSpace(Model.SocialURL))
                        {

#line default
#line hidden
            BeginContext(5210, 30, true);
            WriteLiteral("                            <a");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 5240, "\"", 5263, 1);
#line 128 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
WriteAttributeValue("", 5247, Model.SocialURL, 5247, 16, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(5264, 27, true);
            WriteLiteral("><span>Twitter</span></a>\r\n");
            EndContext();
#line 129 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                        }
                        else
                        {

#line default
#line hidden
            BeginContext(5375, 85, true);
            WriteLiteral("                            <span>This user has not linked a social platform</span>\r\n");
            EndContext();
#line 133 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                        }

#line default
#line hidden
            BeginContext(5487, 91, true);
            WriteLiteral("                    </td>\r\n                </tr>\r\n            </table>\r\n            <br/>\r\n");
            EndContext();
#line 138 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
             if (HttpContextAccessor.HttpContext.Session.Get<int>("UserId") == Model.UserId)
            {
                // If the session UserId is the same as the current profile in the view, we can edit it.

#line default
#line hidden
            BeginContext(5793, 16, true);
            WriteLiteral("                ");
            EndContext();
            BeginContext(5809, 99, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "5073ad3226354c519d6165319fe71ee3", async() => {
                BeginContext(5892, 12, true);
                WriteLiteral("Edit Profile");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_0.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_1.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
            if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
            {
                throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-id", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
            }
            BeginWriteTagHelperAttribute();
#line 141 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                                        WriteLiteral(Model.UserId);

#line default
#line hidden
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = __tagHelperStringValueBuffer;
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-id", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(5908, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 142 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
            }

#line default
#line hidden
            BeginContext(5925, 38, true);
            WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n\r\n");
            EndContext();
#line 147 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
  
        if (HttpContextAccessor.HttpContext.Session.Get<int>("UserId") != 0)
        {

            // If we are logged in we are allowed to comment.
            CommentViewModel comment = new CommentViewModel();

#line default
#line hidden
            BeginContext(6185, 12, true);
            WriteLiteral("            ");
            EndContext();
            BeginContext(6197, 42, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("partial", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "83b2a511d13248d69e2016381bb2c2e7", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper.Name = (string)__tagHelperAttribute_3.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_3);
#line 153 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper.Model = comment;

#line default
#line hidden
            __tagHelperExecutionContext.AddTagHelperAttribute("model", __Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper.Model, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(6239, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 154 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
        }
        else
        {

#line default
#line hidden
            BeginContext(6277, 69, true);
            WriteLiteral("            <br />\r\n            <span>Login to post comments</span>\r\n");
            EndContext();
#line 159 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
        }

#line default
#line hidden
            BeginContext(6360, 8, true);
            WriteLiteral("<br />\r\n");
            EndContext();
#line 162 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
  
    if (Model.Comments.Count == 0)
    {

#line default
#line hidden
            BeginContext(6415, 38, true);
            WriteLiteral("        <span>No comments yet</span>\r\n");
            EndContext();
#line 166 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
    }
    foreach (var comment in Model.Comments)
    {
        ProfileLogic logic = new ProfileLogic();
        string username = logic.GetUsernameForId(comment.SourceUser);

#line default
#line hidden
            BeginContext(6633, 57, true);
            WriteLiteral("        <div class=\"list-group-item\">\r\n            <span>");
            EndContext();
            BeginContext(6690, 98, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "912dee982e0d4fe08dac1a7a333ac8c1", async() => {
                BeginContext(6776, 8, false);
#line 172 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                                                                  Write(username);

#line default
#line hidden
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_0.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_4.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_4);
            if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
            {
                throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-id", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
            }
            BeginWriteTagHelperAttribute();
#line 172 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                                      WriteLiteral(comment.SourceUser);

#line default
#line hidden
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = __tagHelperStringValueBuffer;
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-id", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(6788, 3, true);
            WriteLiteral(" | ");
            EndContext();
            BeginContext(6792, 18, false);
#line 172 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                                                                                  Write(comment.TimePosted);

#line default
#line hidden
            EndContext();
            BeginContext(6810, 24, true);
            WriteLiteral("</span>\r\n            <p>");
            EndContext();
            BeginContext(6835, 19, false);
#line 173 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
          Write(comment.CommentText);

#line default
#line hidden
            EndContext();
            BeginContext(6854, 6, true);
            WriteLiteral("</p>\r\n");
            EndContext();
#line 174 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
             if (HttpContextAccessor.HttpContext.Session.Get<int>("UserId") == comment.SourceUser)
            {

#line default
#line hidden
            BeginContext(6975, 22, true);
            WriteLiteral("                <span>");
            EndContext();
            BeginContext(6997, 135, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "daa4b1d15c734c3f8068291ef3fba7bd", async() => {
                BeginContext(7122, 6, true);
                WriteLiteral("Delete");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_5.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_5);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_6.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_6);
            if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
            {
                throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-commentId", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
            }
            BeginWriteTagHelperAttribute();
#line 176 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                                                      WriteLiteral(comment.CommentId);

#line default
#line hidden
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["commentId"] = __tagHelperStringValueBuffer;
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-commentId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["commentId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            BeginWriteTagHelperAttribute();
#line 176 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
                                                                                                                        WriteLiteral(Model.UserId);

#line default
#line hidden
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = __tagHelperStringValueBuffer;
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-id", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(7132, 9, true);
            WriteLiteral("</span>\r\n");
            EndContext();
#line 177 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
            }

#line default
#line hidden
            BeginContext(7156, 32, true);
            WriteLiteral("        </div>\r\n        <br />\r\n");
            EndContext();
#line 180 "C:\Users\Roy\Documents\Skool\HBO-ICT\S2\Individueel\! Project File\Fortnite-LFG-Hub\Fortnite-LFG-Hub\Views\Profiles\Profile.cshtml"
    }

#line default
#line hidden
            BeginContext(7198, 6, true);
            WriteLiteral("\r\n\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<BusinessLayer.Profile> Html { get; private set; }
    }
}
#pragma warning restore 1591
